name: Benchmark Test With Pytest
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


permissions:
  contents: write
  deployments: write
  packages: write

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Download test data
        run: gh release download release -R StevenSchlechte/testrepoyml -D tests/data
        env:
          GH_TOKEN: ${{ secrets.BENCHMARK_TOKEN }}
      - name: Unzip test data
        run: |
          cd tests/data
          unzip \*.zip
          rm *.zip
          cd ..
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run benchmark tests
        run: pytest ./tests/benchmark_otanalytics.py --benchmark-json output.json
      - name: Store benchmark result - separate results repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
