---
name: Build Release Version

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  test:
    if: startsWith(github.ref, 'refs/tags/')
    uses: './.github/workflows/test.yml'
  create_nightly:
    needs: test
    uses: "platomo/GitHub-workflows/.github/workflows/reusable-create-release-with-assets.yml@main"
    with:
      package-version: ${{ github.ref_name }}
      draft-release: True
      pre-release: False
    secrets: inherit
