---
name: Build Nightly Version

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: './.github/workflows/test.yml'
  create_nightly:
    needs: test
    uses: "platomo/GitHub-workflows/.github/workflows/reusable-create-release-with-assets.yml@main"
    secrets: 
       PLATOMO_BUILDER_ACCESS: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
    with:
      package-version: nightly
      draft-release: True
      pre-release: True
     
      
    
